name: Build and Test Spring Boot Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 23
      uses: actions/setup-java@v3
      with:
        java-version: '23'
        distribution: 'adopt'

    - name: Cache Maven dependencies (optional)
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn clean install -DskipTests=true

    - name: Run tests with Maven
      run: mvn test

    - name: Package Spring Boot Application
      run: mvn package -DskipTests=true

    - name: Build Docker Image
      run: |
        docker build -t surajsh3/kindle:${{ github.sha }} .

    - name: Push Docker Image to Docker Hub (Optional)
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Image to Docker Hub
      run: |
        docker push surajsh3/spring-boot-app:${{ github.sha }}
